import Head from 'next/head'
import Image from 'next/image'
import { ChangeEvent, useState } from 'react';
import { useEffect } from 'react';
import FuckingCard from '../components/FuckingCard';
import FuckingControls from '../components/FuckingControls';
import styles from '../styles/Home.module.css';
import { IFucks } from '../types/commonTypes';

export default function Home({fucks} : IFucks) {
  let [type, setType] = useState('ceil');

  let [pieces, setPieces] = useState(fucks);

  let [from, setFrom] = useState('');
  let [to, setTo] = useState('');

  function handleFilterChange(e: ChangeEvent<HTMLInputElement>): void {
    setPieces(fucks.filter(f => f.title.includes(e.target.value)));
  }

  function handleNewView(newType: string): void {
    setType(newType);
  }

  function handleNewFrom(e: ChangeEvent<HTMLInputElement>): void {
    setFrom(e.target.value);
  }

  function handleNewTo(e: ChangeEvent<HTMLInputElement>): void {
    setTo(e.target.value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>FOaaS ui</title>
        <meta name="description" content="Generate fuck off texts with foaas api" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.heading}>Welcome to FOaaS ui interface</h1>

        <div className={styles.inputsWrapper}>
          <input className={styles.input} value={from} type={'text'} placeholder='from' onChange={handleNewFrom} />
          <input className={styles.input} value={to} type={'text'} placeholder='to' onChange={handleNewTo} />
        </div>
        
        <FuckingControls onChange={handleFilterChange} onNewView={handleNewView} currentView={type}/>

        <ul className={[styles.piecesWrapper, type == 'ceil' && styles.piecesFlexibleWrapper].join(' ')}>
          {
            pieces.map((f, i) => <li key={i}><FuckingCard from={from} to={to} type={type} cardData={f}/></li>)
          }
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="http://foaas.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}foaas.com
        </a>
        <a
          href="https://github.com/Pechenyice"
          target="_blank"
          rel="noopener noreferrer"
        >
          Generated by{' '}German Iskhakov
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const data = await fetch('http://foaas.com/fucks');
  let fucks = await data.text();
  let fucksArr = fucks.split('</tr>');
  fucksArr.pop();
  let results = [];
  for (let f of fucksArr) {
    results.push({
      title: f.split('</td>')[0].split('/')[1],
      text: f.split('</td>')[1]?.split('form')[1].trim().split(':from').join(`<pre>:from</pre>`).split(':to').join(`<pre>:to</pre>`).split(':company').join(`<pre>:company</pre>`).split(':name').join(`<pre>:name</pre>`).split('\'')[1]
    });
  }
  console.log(results)
  return {
    props: {
      fucks: results
    }
  }
}
